'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EnvironmentalStaffForm
    
    '''<summary>
    '''lblUserNm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserNm As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ibHome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibHome As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ibSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibSearch As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''lblPojectoffice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPojectoffice As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtProjectOffice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProjectOffice As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblProjectnumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProjectnumber As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtProjectnumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProjectnumber As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLocation As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLocation As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblPm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPm As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtPm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPm As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescription As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescription As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblPrjbookawarddate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrjbookawarddate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtPrjbookawarddate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrjbookawarddate As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''lblPrjbookcompletiondate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrjbookcompletiondate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtPrjbookcompletiondate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrjbookcompletiondate As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDesignawrddate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesignawrddate As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''lblFyantcptaedconstawddate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFyantcptaedconstawddate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtFyantcptaedconstawddate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFyantcptaedconstawddate As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''lblNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNotes As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNotes As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''txtEnvcontractawardproswpectus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEnvcontractawardproswpectus As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEnvcontractawardoriginal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEnvcontractawardoriginal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEnvcontractawardrevised control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEnvcontractawardrevised As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEnvcontractawardactual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEnvcontractawardactual As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblEnvcontracreq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEnvcontracreq As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlEnvvontracreq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEnvvontracreq As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblEnvsowcompldate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEnvsowcompldate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtEnvsowcompldate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEnvsowcompldate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblContractstatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblContractstatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtContractstatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContractstatus As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblContractbaseawardamt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblContractbaseawardamt As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtContractbaseawardamt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContractbaseawardamt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RegularExpressionValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator1 As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''lblContrbasedoptionawrd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblContrbasedoptionawrd As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtContrbasedoptionawrd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContrbasedoptionawrd As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RepRateRegExVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RepRateRegExVal As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''lblNotesenvcontractsummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNotesenvcontractsummary As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtNotesenvcontractsummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNotesenvcontractsummary As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''txtDuedilligeneceprospectus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDuedilligeneceprospectus As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDuedilligeneceoriginal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDuedilligeneceoriginal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDuedilligenecerevised control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDuedilligenecerevised As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDuedilligeneceactual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDuedilligeneceactual As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkTrafficReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTrafficReport As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkRegulatoryReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRegulatoryReport As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkCulturalAndHistoric control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCulturalAndHistoric As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkUtilityReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUtilityReport As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkAirQualityReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAirQualityReport As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkPhaseIEnvReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPhaseIEnvReport As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkStakeholderReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkStakeholderReport As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkNoiseReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkNoiseReport As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkHydrologyStormwaterReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHydrologyStormwaterReport As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkLBPReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkLBPReport As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkAsbestosReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAsbestosReport As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkWetlandsReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkWetlandsReport As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkEngSpeciesActReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEngSpeciesActReport As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkGeoTechnicalReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkGeoTechnicalReport As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkTopographicSurveyReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTopographicSurveyReport As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkPhaseIIESA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPhaseIIESA As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDueDiligenceReportsNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDueDiligenceReportsNote As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDueDiligenceReportsNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDueDiligenceReportsNote As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''txtAnticipatednepadocumentationkickoffprospectus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAnticipatednepadocumentationkickoffprospectus As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAnticipatednepadocumentationkickofforiginal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAnticipatednepadocumentationkickofforiginal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAnticipatednepadocumentationkickoffrevised control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAnticipatednepadocumentationkickoffrevised As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAnticipatednepadocumentationkickoffactual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAnticipatednepadocumentationkickoffactual As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAnticipateddraftnepadocumentdateprospectus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAnticipateddraftnepadocumentdateprospectus As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAnticipateddraftnepadocumentdateoriginal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAnticipateddraftnepadocumentdateoriginal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAnticipateddraftnepadocumentdaterevised control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAnticipateddraftnepadocumentdaterevised As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAnticipateddraftnepadocumentdateactual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAnticipateddraftnepadocumentdateactual As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAnticipatedfinalnepadocumentprospectus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAnticipatedfinalnepadocumentprospectus As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAnticipatedfinalnepadocumentoriginal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAnticipatedfinalnepadocumentoriginal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAnticipatedfinalnepadocumentrevised control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAnticipatedfinalnepadocumentrevised As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAnticipatedfinalnepadocumentactual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAnticipatedfinalnepadocumentactual As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAnticipatednepadecisionfonsiprospectus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAnticipatednepadecisionfonsiprospectus As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAnticipatednepadecisionfonsioriginal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAnticipatednepadecisionfonsioriginal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAnticipatednepadecisionfonsirevised control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAnticipatednepadecisionfonsirevised As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAnticipatednepadecisionfonsiactual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAnticipatednepadecisionfonsiactual As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblReuirednepadocnlevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReuirednepadocnlevel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlRequirednepadocnlevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRequirednepadocnlevel As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''sdsrclkNEPADoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsrclkNEPADoc As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlNepastatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNepastatus As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblFonsirodsigned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFonsirodsigned As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlfonsirodsigneddate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlfonsirodsigneddate As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblNEPASumStatNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNEPASumStatNotes As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtNEPASumStatNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNEPASumStatNotes As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''lblSupplementaleaeis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSupplementaleaeis As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlSupplemntaleaeis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSupplemntaleaeis As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblPreviouseaseapea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPreviouseaseapea As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtpreviouseaseapea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtpreviouseaseapea As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblDateofcompletionfinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateofcompletionfinal As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDateofcompletionfinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateofcompletionfinal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblDateoffonsi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateoffonsi As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDateoffonsi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateoffonsi As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblEisfinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEisfinal As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtEisfinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEisfinal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblEisrod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEisrod As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtEisrod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEisrod As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblNepasignatory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNepasignatory As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtNepasignatory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNepasignatory As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblNepdocumentationcompletednotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNepdocumentationcompletednotes As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtNepdocumentationcompletednotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNepdocumentationcompletednotes As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''lblNhpacosultation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNhpacosultation As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlNhpaconsultation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNhpaconsultation As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblNhpaletterssent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNhpaletterssent As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtNhpalettersent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNhpalettersent As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblnhpa30days control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblnhpa30days As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtNhpa30days control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNhpa30days As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblNhpamoapa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNhpamoapa As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtNhpamoapa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNhpamoapa As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblNhpasignatory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNhpasignatory As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtNhpasignatory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNhpasignatory As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''hdnNHPA_fk_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnNHPA_fk_1 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lblReuiredmessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReuiredmessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RequiredFieldValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rbPhase1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbPhase1 As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''hdnNHPA_fk_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnNHPA_fk_4 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''firsthdnquestionphase1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents firsthdnquestionphase1 As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''dvPhase1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvPhase1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''dvPhase1AnticipatedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvPhase1AnticipatedDate As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtPhase1AnticipatedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPhase1AnticipatedDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''secondhdnquestionphase1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents secondhdnquestionphase1 As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''dvPhase1ActualDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvPhase1ActualDate As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Div2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtPhase1ActualDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPhase1ActualDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''hdnNHPA_fk_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnNHPA_fk_2 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RequiredFieldValidator2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator2 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rbPhase2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbPhase2 As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''hdnNHPA_fk_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnNHPA_fk_5 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''firsthdnquestionphase2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents firsthdnquestionphase2 As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''dvPhase2Anticipated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvPhase2Anticipated As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''dvPhase2AnticipatedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvPhase2AnticipatedDate As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtPhase2AnticipatedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPhase2AnticipatedDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''secondhdnquestionphase2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents secondhdnquestionphase2 As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''dvPhase2Actual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvPhase2Actual As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''dvPhase2ActualDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvPhase2ActualDate As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtPhase2ActualDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPhase2ActualDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''hdnNHPA_fk_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnNHPA_fk_3 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RequiredFieldValidator3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator3 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rbAdditionalSect106 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbAdditionalSect106 As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''hdnNHPA_fk_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnNHPA_fk_6 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''firsthdnquestionAdditionalSect106 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents firsthdnquestionAdditionalSect106 As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''dvAdditionalSectionAnticipated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvAdditionalSectionAnticipated As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''dvAdditionalSectionAnticipatedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvAdditionalSectionAnticipatedDate As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtAdditionalSect106AnticipatedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAdditionalSect106AnticipatedDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''secondhdnquestionAdditionalSect106 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents secondhdnquestionAdditionalSect106 As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''dvAdditionalSectionActual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvAdditionalSectionActual As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''dvAdditionalSectionActualDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvAdditionalSectionActualDate As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtAdditionalSect106ActualDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAdditionalSect106ActualDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblNhpanotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNhpanotes As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtNhpanotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNhpanotes As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''lblWetlandmitigation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWetlandmitigation As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtWetlandmitigation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWetlandmitigation As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''lblNhpareportsstipulations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNhpareportsstipulations As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtNhpareportsstipulations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNhpareportsstipulations As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''lblEsamitigation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEsamitigation As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtEsamitigation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEsamitigation As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''lblCzma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCzma As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCzma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCzma As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''lblStormwater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStormwater As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtStormwater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStormwater As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
End Class
