'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FSDetails
    
    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''lblFSDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFSDetail As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hlDetailsPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlDetailsPage As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lblReviewStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblUserNm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserNm As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblProjectNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProjectNum As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLastReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastReview As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblProjDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProjDetail As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblProjManagerMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProjManagerMsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblProjPk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProjPk As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLastDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hlProjLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlProjLink As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''fvProjInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fvProjInfo As Global.System.Web.UI.WebControls.FormView
    
    '''<summary>
    '''odsrcProjDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsrcProjDetails As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''gvProjManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvProjManager As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''sdsrcProjManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsrcProjManager As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lblUpdtScopeMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUpdtScopeMsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''gvSubProjScope control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSubProjScope As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''odsrcSubProjScope control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsrcSubProjScope As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''pnlEditScope control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEditScope As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''mupEditScope control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mupEditScope As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''fvEditScope control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fvEditScope As Global.System.Web.UI.WebControls.FormView
    
    '''<summary>
    '''sdscrEditScope control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdscrEditScope As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lblErrorSc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorSc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbUpdtScope control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbUpdtScope As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbCancelEditSc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCancelEditSc As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnEditScope control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditScope As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''mpeEditScope control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeEditScope As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''lblUpdtStatusMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUpdtStatusMsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''gvStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvStatus As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''odsrcAllStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsrcAllStatus As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''pnlEditStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEditStatus As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''mupEditStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mupEditStatus As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''fvEditStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fvEditStatus As Global.System.Web.UI.WebControls.FormView
    
    '''<summary>
    '''sdarcEditStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdarcEditStatus As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lblErrorSt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorSt As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbUpdtStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbUpdtStatus As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbCancelEditSt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCancelEditSt As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnEditStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditStatus As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''mpeEditStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeEditStatus As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''gvSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSchedule As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''sdsrcSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsrcSchedule As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''pnlEditSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEditSchedule As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''mupEditSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mupEditSchedule As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblUpdtMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUpdtMsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnUpdateSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateSchedule As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lbCancelEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCancelEdit As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''cbeSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbeSchedule As Global.AjaxControlToolkit.ConfirmButtonExtender
    
    '''<summary>
    '''rptSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSchedule As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnShowEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShowEdit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''mpeEditSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeEditSchedule As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''lblFundingRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFundingRequired As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTecDisp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTecDisp As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTec As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ibTec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibTec As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblAppropriatedTh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAppropriatedTh As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAppThr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAppThr As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ibApprThr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibApprThr As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblReqstFnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReqstFnd As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblRequestd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRequestd As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ibRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibRequest As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblFutureDisp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFutureDisp As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFuture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFuture As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ibFuture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibFuture As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''pnlTec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTec As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''mupTec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mupTec As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lbTecClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbTecClose As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''mpeTec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeTec As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''pnlApprthr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlApprthr As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''mupApprthr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mupApprthr As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lbApprthrClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbApprthrClose As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''mpeApprthr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeApprthr As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''pnlRequested control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRequested As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''mupRequested control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mupRequested As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lbRequestedClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbRequestedClose As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''mpeRequested control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeRequested As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''pnlFuture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFuture As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''mupFuture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mupFuture As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lbFutureClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbFutureClose As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''mpeFuture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeFuture As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''lblUpdateCommentMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUpdateCommentMsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''gvComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvComments As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''odsrcGetAllComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsrcGetAllComments As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''pnlEditComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEditComment As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''mupEditComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mupEditComment As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''fvEditComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fvEditComment As Global.System.Web.UI.WebControls.FormView
    
    '''<summary>
    '''sdscrEditComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdscrEditComment As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lblErrorCom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorCom As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbUpdtComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbUpdtComment As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbCancelEditCom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCancelEditCom As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnEditComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditComment As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''mpeEditComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeEditComment As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''divProjectHealthandLeadershipHightlights control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divProjectHealthandLeadershipHightlights As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblUpdateCommentMsgExternal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUpdateCommentMsgExternal As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''gvCommentsExternal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvCommentsExternal As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''odsrcGetAllCommentsExternal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsrcGetAllCommentsExternal As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''pnlEditCommentExternal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEditCommentExternal As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''mupEditCommentExternal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mupEditCommentExternal As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''fvEditCommentExternal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fvEditCommentExternal As Global.System.Web.UI.WebControls.FormView
    
    '''<summary>
    '''sdscrEditCommentExternal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdscrEditCommentExternal As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lblErrorComExternal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorComExternal As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbUpdtCommentExternal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbUpdtCommentExternal As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbCancelEditComExternal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCancelEditComExternal As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnEditCommentExternal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditCommentExternal As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''mpeEditCommentExternal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeEditCommentExternal As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''cbDue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDue As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDue As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tweDue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tweDue As Global.AjaxControlToolkit.TextBoxWatermarkExtender
    
    '''<summary>
    '''fvReviewDue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fvReviewDue As Global.System.Web.UI.WebControls.FormView
    
    '''<summary>
    '''lblDuePeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDuePeriod As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''revDue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revDue As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''sdsrcReviewDue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsrcReviewDue As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDeny control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeny As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnReturnByDirector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReturnByDirector As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnApproveByDirector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnApproveByDirector As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnApprove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnApprove As Global.System.Web.UI.WebControls.Button
End Class
