'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SubmittedReviewList

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''lblRole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRole As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UCMenuAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCMenuAdmin As Global.CFMISNew.UCMenuAdmin

    '''<summary>
    '''UCMenuGeneral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCMenuGeneral As Global.CFMISNew.UCMenuGeneral

    '''<summary>
    '''UCMenuEnvEngineer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCMenuEnvEngineer As Global.CFMISNew.UCMenuEnvEngineer

    '''<summary>
    '''UCMenuEnvDirector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCMenuEnvDirector As Global.CFMISNew.UCMenuGeneral

    '''<summary>
    '''UCMenuSustainability control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCMenuSustainability As Global.CFMISNew.UCMenuSustainability

    '''<summary>
    '''lblAccessMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccessMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlFinalReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFinalReview As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblReviewListHdg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewListHdg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvSubmittedReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSubmittedReview As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''odsrcListOfSubmittedReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsrcListOfSubmittedReview As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''btnViewAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnViewAll As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlEastReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEastReview As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblReviewForDirectorEast control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewForDirectorEast As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvSubmittedReviewForEastDirector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSubmittedReviewForEastDirector As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''odsrcReviewForEastDirector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsrcReviewForEastDirector As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''pnlWestReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlWestReview As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblReviewForDirectorWest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewForDirectorWest As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvSubmittedReviewForWestDirector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSubmittedReviewForWestDirector As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''odsrcReviewForWestDirector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsrcReviewForWestDirector As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''pnlCentralReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCentralReview As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblReviewForDirectorCentral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewForDirectorCentral As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvSubmittedReviewForCentralDirector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSubmittedReviewForCentralDirector As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''odsrcSubmittedReviewCentralDirector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsrcSubmittedReviewCentralDirector As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''pnlNCAReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNCAReview As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblReviewForDirectorNCA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewForDirectorNCA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvSubmittedReviewForNCADirector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSubmittedReviewForNCADirector As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''odsrcNCAReviewList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsrcNCAReviewList As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
