'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MaintainLookup

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''aLookuoList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aLookuoList As Global.AjaxControlToolkit.Accordion

    '''<summary>
    '''apProjStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents apProjStatus As Global.AjaxControlToolkit.AccordionPane

    '''<summary>
    '''gvProjStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvProjStatus As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''odsrcStatusList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsrcStatusList As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''apProjCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents apProjCategory As Global.AjaxControlToolkit.AccordionPane

    '''<summary>
    '''gvProgCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvProgCat As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''odsrcAddNewProjCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsrcAddNewProjCategory As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''apProjSubCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents apProjSubCategory As Global.AjaxControlToolkit.AccordionPane

    '''<summary>
    '''gvProgSubCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvProgSubCat As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''odsrcProjSubCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsrcProjSubCategory As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''apProjDeliveryMethod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents apProjDeliveryMethod As Global.AjaxControlToolkit.AccordionPane

    '''<summary>
    '''gvProjDeliveryMthd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvProjDeliveryMthd As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''odsrcProjDeliveryMthd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsrcProjDeliveryMthd As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
